package imdb.streamings;

public enum Categoria {
    TOP_10_BRASIL, EXCLUSIVE_PRIME, PARA_MARATONAR_FINAL_SEMANA, SO_NO_NETFLIX,
    DE_ARREPIAR, MORRER_DE_RIR, SERIAL_KILLERS, SERIES_POLICIAIS, LOVE_STORY,
    DE_TIRAR_O_FOLEGO, STAR_WARS, MARVEL, DISNEY, PIXAR, DISCOVERY;
}
